# version: '3'
# services:
#   api:
#     image: danieldaum/labfull_backend
#     ports:
#       - 80:8000
#     environment:
#       - DBTYPE=${DBTYPE}
#       - DBUSER=${DBUSER}
#       - DBPASS=${DBPASS}
#       - DBHOST=${DBHOST}
#       - DBPORT=${DBPORT}
#       - DBNAME=${DBNAME}


version: '3'
services:
  api:
    build: .
    ports:
      - 8000:8000
    env_file:
      - ./.env


#       - KEY=${KEY}
#       - ALGO=${ALGO}
#       - EXPIRE=${EXPIRE}
#       - ROLE=${ROLE}
#       - EMAIL=${EMAIL}
#       - EMAIL_SERVER=${EMAIL_SERVER}
#       - EMAIL_SERVER_KEY=${EMAIL_SERVER_KEY}
#       - DBNAME_TEST=${DBNAME_TEST}
