"""email verify table relationship reassociation

Revision ID: 2bf73640bd81
Revises: 9cc7e378b03d
Create Date: 2023-01-25 00:52:28.283752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bf73640bd81'
down_revision = '9cc7e378b03d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('email_verification_users_email_fkey', 'email_verification', type_='foreignkey')
    op.create_foreign_key(None, 'email_verification', 'unactivated_users', ['users_id'], ['id'])
    op.create_foreign_key(None, 'email_verification', 'unactivated_users', ['users_email'], ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'email_verification', type_='foreignkey')
    op.drop_constraint(None, 'email_verification', type_='foreignkey')
    op.create_foreign_key('email_verification_users_email_fkey', 'email_verification', 'users', ['users_email'], ['email'])
    # ### end Alembic commands ###
