"""added daily forecast table

Revision ID: 608d971cb7e6
Revises: b840909c5df5
Create Date: 2023-01-21 11:24:53.310221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '608d971cb7e6'
down_revision = 'b840909c5df5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_forecast',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resort_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.Column('relative_date', sa.String(length=50), nullable=True),
    sa.Column('start_time', sa.Date(), nullable=False),
    sa.Column('end_time', sa.Date(), nullable=False),
    sa.Column('is_daytime', sa.Boolean(), nullable=True),
    sa.Column('temperature', sa.Integer(), nullable=True),
    sa.Column('temperature_unit', sa.String(length=1), nullable=True),
    sa.Column('temperature_trend', sa.String(length=255), nullable=True),
    sa.Column('wind_speed', sa.String(length=100), nullable=True),
    sa.Column('wind_direction', sa.String(length=5), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('short_forecast', sa.String(length=50), nullable=True),
    sa.Column('detailed_forecast', sa.String(length=100), nullable=True),
    sa.Column('last_updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('valid_from', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('valid_to', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['resort_id'], ['resorts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_forecast')
    # ### end Alembic commands ###
