"""added generated tokens table

Revision ID: 701872aa5262
Revises: 8571b019518d
Create Date: 2023-01-24 20:47:41.557869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '701872aa5262'
down_revision = '8571b019518d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generated_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('users_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('generated_tokens')
    # ### end Alembic commands ###
