"""added zip column to resorts

Revision ID: e37baff9aa9a
Revises: 2bf73640bd81
Create Date: 2023-01-29 18:32:09.130065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e37baff9aa9a'
down_revision = '2bf73640bd81'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resorts', sa.Column('zip', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resorts', 'zip')
    # ### end Alembic commands ###
